### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dan2735** [C0nw0nk/Garrys-Mod-Family-Sharing#1]
Wouldn't having all the setting variables be global cause issues?

**Comment by C0nw0nk** [comment]
No because only 3 are shared the rest are server sided. It would only be a problem if other addons on your server used the same string name.

The only reason I removed them from being local values is because of the split I made between the two "if SERVER then" statements.

Example :
`if SERVER then
local value = "lol"
end`
`--Can't be read from a separate statement.`
`if SERVER then
print(value)
end`
To print the value will return nil.

In the next update I release on the script I localized the shared settings. As well as a few others I missed. As well as to allow the script to work on servers that don't use ULX. But I recommend to not localize any of the settings inside the "If SERVER" block or you will find you break the script and it won't work.

**Comment by C0nw0nk** [comment]
https://github.com/C0nw0nk/Garrys-Mod-Family-Sharing/commit/3d3ab1a8d7547218496b06b068e966cee51fccb0

Updated to localize the last of the values that can be but with the next release i have done it has allot of changes i will make it possible to localize those settings again in the next release.
