### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DutchPatrick** [C0nw0nk/Garrys-Mod-Family-Sharing#5]
Is this right?
[ERROR] lua/autorun/familysharing.lua:166: FamilySharing: Failed API call for
(Error: unsuccessful)

  1. error - [C]:-1
   2. onfailure - lua/autorun/familysharing.lua:166
    3. unknown - lua/includes/modules/http.lua:42

I have seen users with shared account that has been banned on their main.

**Comment by mralimac** [comment]
Did you add an API key?

**Comment by DutchPatrick** [comment]
Yes.

Op 3 jun. 2017 4:37 p.m. schreef "Ali Mac" <notifications@github.com>:

**Comment by C0nw0nk** [comment]
Are you running it on localhost or a publicly accessible server.

Can be a great number of reasons even down to a firewall blocking ports. localhost machines this does not work on. I suggest if you have not already installed a "srcds" (dedicated server) instance and run it on that.

It has always worked fine on dedicated machines / server instances just not from your garrysmod lua folder installed on your local pc where you play the game. Hence why you should install it on a dedicated server (srcds).

**Comment by DutchPatrick** [comment]
I have it running on a accessible server l, yes with srcds linux.

Op 3 jun. 2017 18:45 schreef "C0nw0nk" <notifications@github.com>:

**Comment by C0nw0nk** [comment]
Check your firewalls if you block ports access from internet it has to communicate over TCP port 80 and depending on if steam has started forcing HTTPS or not TCP port 443.

https://github.com/C0nw0nk/Garrys-Mod-Family-Sharing/blob/master/garrysmod/lua/autorun/familysharing.lua#L142

Contact your host and ask them but there is nothing wrong with the script plenty of people use it and it communicates just fine problems like you are having indicate to something else at play.

If you connect yourself on a shared account and their is no error displayed like in your original comment, Then you know it is not the script but some kind of connection problem with your server and steam's developer API site. Some sites and servers get blocked from connecting / communicating with external sources due to reasons of spam/flood/dos etc.

There could be so many reasons you are best debugging yourself and seeing if it shows that error for every single shared account that connects or only a few every once in while. (If it does not do it for everyone it is some kind of connectivity issue)
