### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by pumab9** [C0nw0nk/Garrys-Mod-Family-Sharing#7]
[ERROR] lua/autorun/familysharing.lua:264: FamilySharing: Invalid Steam API response for 0 | steamid

  1. error - [C]:-1
   2. onsuccess - lua/autorun/familysharing.lua:264
    3. unknown - lua/includes/modules/http.lua:35

**Comment by mralimac** [comment]
Did you set an API Key on [line 17](https://github.com/C0nw0nk/Garrys-Mod-Family-Sharing/blob/master/garrysmod/lua/autorun/familysharing.lua#L17)?

**Comment by pumab9** [comment]
@mralimac Yes ! I have my API key there, your script already baned a lot of people on my server for the past month. I just recently recived this error randomly, but I guess it still works?

**Comment by mralimac** [comment]
Its not my script. I'm just helping

It looks like the SteamID is being returned as null. I don't know why its happening

**Comment by C0nw0nk** [comment]
I suspect that just like the "steamcommunity.com" goes offline and your friends list will go down it has the same impact on the ability to connect to their API, It is not bad since the script won't block anyone out or anything silly. Just something that can not be controlled from the script if Steam's servers go down or under maintenance etc.

**Comment by pumab9** [comment]
@C0nw0nk I see ! Thank you for clarifying !
